include make/x86
include make/makeIncl

x86: compressed
#	$(CC) -c */*.c -Iinclude $(CFLAGS)
#	$(MAKE) -C arch/x86 arch
#	$(LD) $(LDFLAGS) -o $(OUT) *.o

compressed:
	$(CC) $(CFLAGS) arch/x86/boot/compressed/*.c
	$(CC) $(CFLAGS) vga/*.c
	$(AS) arch/x86/boot/compressed/boot.s $(ASFLAGS) -o ./boot.o
	$(LD) $(LDFLAGS) -o $(OUT) *.o

asm:
	$(CC) -c -S -Iinclude $(CFLAGS) -m32 */*.c
